apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 840538141485.dkr.ecr.us-east-1.amazonaws.com/demo-frontend-bsakowski
  newName: 840538141485.dkr.ecr.us-east-1.amazonaws.com/demo-frontend-bsakowski
  newTag: 16147e6d
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
